### ISSUE TITLE
Meta Tags in <body> instead >head>. Why?

### ISSUE THREAD

**Issue by boosterdigital** [Yoast/yoast-components#108]
I set correctly yoast plugin in backend, but yoast code appears in <body> ... </body> instead of <head>. Can someone help me?

Thanks

**Comment by atimmer** [comment]
Welcome @boosterdigital. This repository is for a specific part of Yoast SEO, so this is not the most appropriate venue for your request. Furthermore, this is not a bug, but a support request. We use GitHub exclusively for (well-documented) bug reports, so we cannot help you here.

To receive free support for WordPress SEO we have the following channels:
* [Yoast Knowledge base](http://kb.yoast.com)
* [Support forums](https://wordpress.org/support/plugin/wordpress-seo) on WordPress.org

Or if you want personal support via email, you can purchase [WordPress SEO Premium](https://yoast.com/wordpress/plugins/seo-premium/).

Thanks for your understanding.
