### ISSUE TITLE
Usage of the search result preview.

### ISSUE THREAD

**Issue by andizer** [Yoast/yoast-components#120]
We've added a search review component to this repository three month ago. It look likes this components isn't in use yet, however the search-result-preview in YoastSEO.js is still being maintained. This means the functionality of the component is not up-to-date when compored to the YoastSEO.js variant. 

I think it's good to have a clear decision about the preview we are going to use to make sure there is one preview being maintained.

**Comment by IreneStr** [comment]
We are currently rebuilding the snippet preview in React: https://github.com/Yoast/yoast-components/issues/155
