### ISSUE TITLE
New colors for My Yoast

### ISSUE THREAD

**Issue by hedgefield** [Yoast/yoast-components#133]
For my.yoast we need a set of new colors (most use existing palettes but there are a few new ones):

- $color_chevron: `palette_grey_medium_dark (#888888)` (this is the arrow that expands or collapses a div)
- $color_round_button: NEW `palette_green_medium (#64a60a)` (change current palette_green_medium to palette_green_dark!)
- $color_button_my_yoast: `palette_blue (#0075b3)`
- $color_link_my_yoast: `palette_blue (#0075b3)`
- $color_toggle_on_knob: `palette_blue (#0075b3)`
- $color_toggle_on_gutter: NEW `palette blue_light (#a9a9ce)`
- $color_toggle_off_knob: `palette_grey_disabled (#a0a5aa)`
- $color_toggle_off_gutter: `palette_grey_medium (#cccccc)`
- $nav_my_yoast: `palette_pink_dark (#a4286a)`
- $background: `palette_grey_light (#f1f1f1)`
- $input_my_yoast: `palette_grey_light (#f1f1f1)`
- $zebra_stripe: `palette_grey_ultra_light (#f7f7f7)`

I'd submit a pull request myself but I'm not sure what the ramifications are of changing those values 🙃  Thanks!

**Comment by hedgefield** [comment]
Hang on, I see you map these palettes to colors, and it's probably not smart to re-use existing ones for the new my.yoast elements, so I need a minute to compile a new list of colors I'll need.

**Comment by hedgefield** [comment]
I've updated the OP with the full list. ☝️

**Comment by afercia** [comment]
I think we're already using `$color_green_medium` [for the extensions styles](https://github.com/Yoast/wordpress-seo/blob/5d717e28d52b432c80a44055581cc0688d9246e0/css/src/extensions.scss#L191) (License Manager), even if I think the new License Manager hasn't been bundled with the plugin yet.

Wouldn't it be better to avoid renaming the `$palette_*` colors and just map new ones to meaningful `$color_*`? After all, we shouldn't care too much about the names of the palette ones, as long as the `$color_*` are understandable.

**Comment by hedgefield** [comment]
We could, although there's something to be said for keeping them in sync with one another. I believe there's a background_light color that uses the ultra_light palette for instance, and things like that. Might get confusing if more are added.

If it's too much of a hassle though we could go with `palette_green_medium_light`.
