### ISSUE TITLE
Reactify SnippetPreview editor

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#155]
We are going to Reactify the current snippet preview editor. 

### Desktop snippet preview
![schermafbeelding 2017-07-14 om 11 06 02](https://user-images.githubusercontent.com/17744553/28206629-f1a0b3d2-6886-11e7-9fc6-4e6030dd39e0.png)
![schermafbeelding 2017-07-14 om 11 33 33](https://user-images.githubusercontent.com/17744553/28206985-5c463f12-6888-11e7-9981-25ccf0438ac6.png)

### Mobile snippet preview
![schermafbeelding 2017-07-14 om 11 06 10](https://user-images.githubusercontent.com/17744553/28206632-f2f5b64c-6886-11e7-84aa-e6f095ef9853.png)
![schermafbeelding 2017-07-14 om 11 34 01](https://user-images.githubusercontent.com/17744553/28206991-5e8f6dde-6888-11e7-80d1-4b762ef7be14.png)

### Additions to the current snippet preview editor
- Using Draft.js editor as input field: https://github.com/Yoast/yoast-components/issues/111
- Autocompletion and decoration for variables beginning with %%: https://github.com/Yoast/yoast-components/issues/112 

### Requirements
- The Reactified version should work **exactly** the same as our current editor (except for the above mentioned draft.js decorators and autocompletion). Therefore always use the current editor as a reference.
- The snippet preview should be accessible. Please consult regularly with @afercia about this topic. Also keep in mind his comments about Draft.js in Yoast/yoast-components#111.
- The snippet preview should be responsive. Please always test whether your implementations work flawless on smaller screens.

### NB
- You can use the SearchResultEditor that was built last summer as an inspiration. However, some things have been changed since then, and that implementation isn't flawless. When in doubt, always use the current snippet preview editor from the plugin as a reference.
- All icons can be found here: https://github.com/Yoast/yoast-components/issues/156

#### Editor
- Progress bar component #157 
- Input field component #159
    - Second iteration: #205
- Form Group component #160 
- Help Button component #164
- Help Panel component #163 
- Button component #165
- Icon Button component #166
- Preview Toggle component #167
- Snippet Preview Component #169

#### Redux
- SnippetPreviewReducer + actions #162 
- rootReducer https://github.com/Yoast/wordpress-seo/issues/7593

#### Container
- Snippet Preview container https://github.com/Yoast/wordpress-seo/issues/7594

**Comment by afercia** [comment]
General initial consideration about autocompletion:
Will it be just a "type-ahead" completion or it will display a list of suggestions attached to the bottom of the field?
In the second case, it should be implemented like a combobox. There are example of this in WordPress and in Gutenberg:
- WP insert link in the old editor (jQuery)
- WP tags suggestions in the tags metabox and in the Quick Edit tags textarea (jQuery)
- Gutenberg tags suggestions: React! See https://github.com/WordPress/gutenberg/pull/1141 where the only thing to improve is  that is shouldn't use `throttle`, should use `debounce` instead.

**Comment by IreneStr** [comment]
@afercia Thanks! We are aiming for a list of suggestions, as shown in the screenshots in #112

**Comment by hedgefield** [comment]
These are the icons used:

For @IreneStr:

Eye: http://fontawesome.io/icon/eye/
Questionmark: http://fontawesome.io/icon/question-circle/
Pencil: http://fontawesome.io/icon/pencil/
Mobile: http://fontawesome.io/icon/mobile/
Desktop: http://fontawesome.io/icon/desktop/

The questionsmark seems slightly different than the one we use in the plugin now, not sure where it's from. Please replace it with the fontawesome version everywhere (that's the one we use in My Yoast as well).

**Comment by atimmer** [comment]
I want to add one thing: Ship early and often!

Build the smallest thing you can and add it to the plugin. This is the best way to ensure compatibility. My suggestion is to start with the editor part of the snippet preview. Also because it adds the most (with draftJS).

**Comment by moorscode** [comment]
When picking up this issue, please make a specifications document on the snippet preview on how it works *exactly*.

There is no way to test if it works *exactly* as it does at the moment without detailed specifications.
It also makes writing tests for the code much easier.
