### ISSUE TITLE
Snippet preview icons

### ISSUE THREAD

**Issue by hedgefield** [Yoast/yoast-components#156]
Eye: http://fontawesome.io/icon/eye/
Questionmark: http://fontawesome.io/icon/question-circle/
Pencil: http://fontawesome.io/icon/pencil/
Mobile: http://fontawesome.io/icon/mobile/
Desktop: http://fontawesome.io/icon/desktop/

The questionsmark seems slightly different than the one we use in the plugin now, not sure where it's from. Please replace it with the fontawesome version everywhere (that's the one we use in My Yoast as well).

**Comment by atimmer** [comment]
The SVG code is present here: https://github.com/Yoast/YoastSEO.js/blob/develop/css/_icons.scss
