### ISSUE TITLE
Implement InputField component using Draft.js

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#159]
Implement a `InputField` component using Draft.js
![schermafbeelding_2017-07-14_om_12_05_37](https://user-images.githubusercontent.com/17744553/28211352-79606406-689c-11e7-985f-caff84208927.png)

Optional features of the input field:
- Placeholder text (like in the SEO title and Meta description input fields above). Please make the placeholder text translatable using `react-intl`.
- Being resizable (like the Meta description input field above). One-line input field should stay one line!

Please keep in mind the accessibility considerations discussed in related issue #111.

Draft.js docs: https://draftjs.org/docs/overview.html

Please put this component in the SnippetPreview folder.

**Comment by IreneStr** [comment]
Related #111

**Comment by afercia** [comment]
I'd consider to make the input/textarea have an associated label by default. There are no cases I can think of where this component _without_ an associated label would be a correct implementation 🙂 

The label should be associated to the field/textarea using for/id attributes (not wrapping the element). For that, there's the need of unique IDs. One smart way to implement this could be what WP Gutenberg does with a higher order component called [withInstanceId](https://github.com/WordPress/gutenberg/blob/2d9129479c9106776e8e83a7f89222556b234161/components/higher-order/with-instance-id/index.js).

Optionally, the label could be visually hidden with a `screen-reader-text` CSS class, passing some prop to the component.

**Comment by afercia** [comment]
Looking a bit into this, I think draft.js doesn't provide a way to associate a label element with for/id attributes. I'd like to be wrong. There is an `aria-label` prop, or maybe we could wrap the input in a label (not ideal).

**Comment by afercia** [comment]
After a bit of research, it appears draft.js is not designed to natively emulate input fields (single line). It's a rich text editor, designed to replace textarea elements.

Seems it is not possible to override the default styles draft.js apples to the content area, specifically:
```
var contentStyle = {
    outline: 'none',
    whiteSpace: 'pre-wrap',
    wordWrap: 'break-word'
};
```

It is possible to apply a CSS class to all the blocks in the content, for example:
```
const blockStyles = contentBlock => {
	return "my-class";
};
```

and then pass this as prop:
`blockStyleFn={ blockStyles }`

this would require to use our own stylesheet, let's say an `App.css` where to include our rule:
```
.my-class {
	white-space: nowrap !important
	word-wrap: normal !important;
}
```

For example, also the draft.js plugins https://www.draft-js-plugins.com/plugin/mention style some elements this way.

Alternatively, there is a plugin (haven't tested):
https://github.com/icelab/draft-js-single-line-plugin
which basically replaces the default content block with its own one.

**Comment by IreneStr** [comment]
Requirements for the input field content:
- [ ] Everything on one line (single-line input field)
- [ ] Copy & paste
- [ ] Newlines are prevented, also when pasting
- [ ] Backspace and delete
- [ ] Moving through the content using the arrow keys
- [ ] Possible to start typing anywhere in the content, also at the very beginning
