### ISSUE TITLE
Implement a generic Button component

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#165]
Using styled components, implement a generic `Button` component with the following props:

- onClick `function` The function that is called when the button is clicked
- text `string` The text within the button

![schermafbeelding_2017-07-14_om_12_05_37](https://user-images.githubusercontent.com/17744553/28518402-05300dd8-7068-11e7-9e9d-67a0d09d982e.png)

Please put this component in the Plugin folder (the folder containing SnippetPreview and ContentAnalysis).

**Comment by Xyfi** [comment]
This will require 2 different components, since implementing a button with an icon is a whole different ballgame. I propose a `Button` and an `IconButton`.
