### ISSUE TITLE
Implement IconTextButton component

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#166]
Using styled components, implement a IconTextButton component  based on the Button component (#165)
- onClick `function` The function that is called when the button is clicked
- text `string` The text within the button
- icon `string` The icon in the button 
![schermafbeelding_2017-07-14_om_12_05_37](https://user-images.githubusercontent.com/17744553/28518654-ec8ed466-7068-11e7-9cb0-4add2e5a88ac.png)

Required: #165

Please put this component in the SnippetPreview folder.

**Comment by IreneStr** [comment]
Please rename to IconTextButton

**Comment by Xyfi** [comment]
This issue will be resolved in issue #190 by implementing the IconButton in a way it can be used with or without text.
