### ISSUE TITLE
Implement AnalysisHeader component

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#192]
Using styled components, implement an AnalysisHeader component with the following props:

- isOpen `bool` Whether the header is collapsed
- headerTitle `string` The segment title.
- children ` PropTypes.oneOfType( [
		PropTypes.arrayOf( PropTypes.node ),
		PropTypes.node,
	] )` The list items

<img width="644" alt="seo_analysis_reactified_4_psd___100___layer_2__rgb_8__" src="https://user-images.githubusercontent.com/6073772/29068418-0d7a8628-7c37-11e7-8b8c-9d162b1dfafd.png">

You can use the collapsible header in the My Yoast project as an source of inspiration: `my-yoast/client/src/components/CollapsibleHeader.js`.

Please put this component in the ContentAnalysis folder.

NB: this issue may change based on the discussion in https://github.com/Yoast/roadmap/issues/4

**Comment by hedgefield** [comment]
Please give this component a more unique name, since there will also be a different collapsibleheader to contain this component (which is styled more closely to the My Yoast one). Something like `AnalysisHeader` would work better for this.

**Comment by Xyfi** [comment]
Seeing what it does, maybe `AnalysisCollapsible` would be a more suitable name.
