### ISSUE TITLE
Reactification overview issue

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#195]
Yoast-components:
- Overview issue snippet preview: #155 
- Overview issue content analysis: #193 

Wordpress-seo:
- Root reducer: https://github.com/Yoast/wordpress-seo/issues/7593

**Comment by hedgefield** [comment]
For context, the entire Reactified metabox that we will have at the end of phase 3:

![metabox react](https://user-images.githubusercontent.com/6073772/29069438-49fd9b40-7c3b-11e7-9d9b-815a17661501.png)

**Comment by IreneStr** [comment]
This issue is not relevant anymore
