### ISSUE TITLE
Reactify Help Center - invocation and navigation

### ISSUE THREAD

**Issue by hedgefield** [Yoast/yoast-components#196]
The way the new Help Center will be invoked is very similar to the current design.

- There is a button that toggles the display of the paper that holds the Help Center.
- Within the paper is a horizontal tab navigation that toggles the display of the individual pages.

![help closed](https://user-images.githubusercontent.com/6073772/28922605-2ada3626-785b-11e7-8f5e-8f40580e2c23.png)

![help kb](https://user-images.githubusercontent.com/6073772/28922610-2eebbfbe-785b-11e7-8686-2a34ba6bc5f9.png)

## The button
The button is of the same class as all the other My Yoast buttons. It has an icon (fa-question-circle), a label (`Need help?`) and a chevron that points down when the HC is closed, and points up when the HC is open.

The button is horizontally aligned to the middle of the content column. In My Yoast, it is vertically aligned to the top of the page. In the plugin, it appears in the same place it does now (but also middle-aligned).

If possible, clicking the button should animate the opening of the help center paper, it shouldn't just appear. It's fine if the paper is blank during this transition.

## The tabs
The tab navigation is the same class as the other tabs in My Yoast. It holds three items: `Video tutorial`, `Knowledge base` and `Get support`. Note: on the Titles & Meta page in the plugin, it has a fourth tab: `Template explanation`, the contents of which are described in a separate issue. Therefore the tabs should not have a fixed width (if they didn't already).

## The paper
The help center container itself should stretch to 100% of the content column, using the same margin that the rest of the content uses. I hope this is clear, but when in doubt, come and ask me.

The default (min-)height of the paper is 432px (give or take, I know this depends on the font size and paddings/margins eventually). Including the toggle above it it is ~500px.

The font size should be inherited from the default body text.

The padding is 40px left and right, and 24px top and bottom.

**Comment by afercia** [comment]
Re: Tabs:
this would be a good opportunity to build an ARIA tabbed interface component. Interaction details and code examples (sorry, no React): https://www.w3.org/TR/wai-aria-practices/#tabpanel

**Comment by afercia** [comment]
Of course, _Google knows_ so [from a very quick search](https://www.google.it/search?q=react+aria+tabs&oq=react+aria+tabs&aqs=chrome..69i57.2551j0j7&sourceid=chrome&ie=UTF-8) seems there are already some React accessible tabs components:
https://github.com/reactjs/react-tabs
https://github.com/stowball/react-accessible-tabs

no demo, need testing
https://github.com/patrik-piskay/react-tabs-redux

**Comment by IreneStr** [comment]
Fixed in #303
