### ISSUE TITLE
Reactify Help Center - video tab

### ISSUE THREAD

**Issue by hedgefield** [Yoast/yoast-components#197]
The video page functions the same as it does now. I've marked any changes I've made in bold, the rest can pretty much be copied one-to-one.

![help video](https://user-images.githubusercontent.com/6073772/28927172-25fabdd8-786a-11e7-828d-2ab64a31770f.png)

- There are two columns, which together are **aligned with margin: 0 auto**.
- The left column has the embedded video. Its size is roughly 560x320 (could differ based on padding, it doesn't have to be exactly that).
- The right column (400px wide) has upsells (two in free, one in premium), stacked vertically and top-aligned. **I've removed the rounded border around the upsells, and the premium upsell has a border-bottom to separate the two.**
- When the browser window becomes too small/mobile for the two columns to display side-by-side, the upsells slide under the video, making it one column.
- When the window goes below 782px in width (wordpress' tablet breakpoint), the video should become responsive and scale to fill the horizontal space (while maintaining its aspect ratio).

See #196 for padding and font stuff.

**Comment by IreneStr** [comment]
Fixed in https://github.com/Yoast/wordpress-seo/pull/7948
