### ISSUE TITLE
Reactify Help Center - KB tab

### ISSUE THREAD

**Issue by hedgefield** [Yoast/yoast-components#198]
The KB page functions largely the same as it does now. I've marked any changes I've made in bold, the rest can pretty much be copied one-to-one.

![help kb search](https://user-images.githubusercontent.com/6073772/28928150-c9884d2e-786c-11e7-9e47-5dc494c07779.png)

![help kb](https://user-images.githubusercontent.com/6073772/28928102-abd39946-786c-11e7-8329-d83233cbd965.png)

![help center kb article](https://user-images.githubusercontent.com/6073772/29705842-0dda7d84-8980-11e7-825b-13fede5a3bd4.png)

- When you open the page, it displays a search bar with **an icon and a button. The placeholder reads `Type here to search the Yoast Knowledge Base`.**
- When you type something, you have to hit enter (or the button) to submit. No live search or autocomplete (yet).
- The entire paper can scale vertically depending on how many results need to be shown.
- **The results are shown in a zebra stripe list.**
- Navigating away to another tab or closing the help center clears the search.

**Comment by IreneStr** [comment]
Fixed in https://github.com/Yoast/wordpress-seo/pull/7948
