### ISSUE TITLE
Reactify Help Center - support tab

### ISSUE THREAD

**Issue by hedgefield** [Yoast/yoast-components#199]
The support page functionality is the same as it is now.

![help support free](https://user-images.githubusercontent.com/6073772/28928239-0482c210-786d-11e7-9a73-0b48e0008878.png)

![help support](https://user-images.githubusercontent.com/6073772/28928210-f2c6b13a-786c-11e7-850d-65db490706c1.png)

- In the free plugin, this tab shows an upsell for premium. The copy for this is the same as it is now, I've only moved the icon to the left.
- If you have premium, this tab is blank, but opening it triggers the Helpscout modal, same as we do now. Clicking outside of the modal closes it. The modal only reappears if you click on the Get support tab again.

**Comment by afercia** [comment]
Question:
> If you have premium, this tab is blank, but opening it triggers the Helpscout modal, same as we do now. Clicking outside of the modal closes it. The modal only reappears if you click on the Get support tab again.

What does happen when closing the modal? To my understanding, the underlying tab is empty (I don't see any content within the tab in the mockup above). Or should the previously displayed tab stay there?
I'm afraid this interaction would break the expected interaction with the tabs.

Note: the modal needs a way to be closed using only the keyboard.

**Comment by hedgefield** [comment]
What you quoted is indeed how it works in our current release. I'd rather have integrated the form into the tab, but I understood that was more complicated to do. The empty tab after closing the modal is indeed strange. Maybe we can add a button to re-open the modal, although that feels messy too.

In regards to the modal itself, I don't know what the possibilities are to customize it, but I would much prefer to add a Close button too. Only being able to close by clicking next to the modal is weird.

**Comment by IreneStr** [comment]
@hedgefield Any new decisions about the design? Should we include a Close button? If so, could you please provide us with a new mockup asap?

**Comment by hedgefield** [comment]
Documenting our offline discussion about this this morning: based on the timeframe for this release, using the Helpscout popup was decided to be the way to go to not slow down development (again). Like I mentioned, it's functionally identical to how this works in the plugin now, so that's okay, there is no change or regression. After this release, we can investigate a way to integrate these fields into the tab itself (which is the strong preference of those involved).

**Comment by IreneStr** [comment]
Discussed with @hedgefield: Button will be green with white letters (for now).

**Comment by IreneStr** [comment]
Fixed in https://github.com/Yoast/wordpress-seo/pull/7948
