### ISSUE TITLE
Reactify Help Center - Templates tab

### ISSUE THREAD

**Issue by hedgefield** [Yoast/yoast-components#200]
This is a special tab that only appears on the `Titles & Meta` page in the plugin. Currently they appear as three tabs (Templates explanation, Basic Variables and Advanced Variables), but in this new version I've combined them into one - for available space reasons in the tab menu on mobile, and simply because the content belongs together. So please take the content from those three tabs and put it below each other. For font sizes etc see #196 or talk to me.

![help templates](https://user-images.githubusercontent.com/6073772/28929071-638e4822-786f-11e7-9082-32bd6178f8f3.png)

**Comment by IreneStr** [comment]
Fixed in https://github.com/Yoast/wordpress-seo/pull/7948
Separate issue for combining three template tabs into one: #328
