### ISSUE TITLE
Make Snippet Preview buttons consistent with other metabox/wordpress buttons

### ISSUE THREAD

**Issue by Xyfi** [Yoast/yoast-components#201]
Currently the button component styling in `wordpress-seo`, which this library's button is styled after, has some issues:

* It behaves differently on chrome and firefox/safari, which has to do with the `focus` behaviours in different browsers, not sure whether this can be fixed
* Could use some `hover` and `active` specific styles to emphasise it's a button, like most default wordpress buttons

Since we are rebuilding the Snippet preview from scratch, it would be a good idea to look into redesigning this component.

**Comment by hedgefield** [comment]
We are still exploring what kind of 'branded' buttons we can use in the wordpress environment. The orange ones from the site or the green ones from my yoast are obvious candidates, but within wordpress we also have to take into account the color scheme that users can select, something with bold color might clash with the rest of their admin area.

As a start, take a look at the other buttons around the post edit screen. Like you mentioned, they look very similar, but have a good hover/click/focus state. We do in fact already have one like that in the Social>Facebook tab, next to the image upload field. See if you can apply that styling to the snippet preview buttons also.
