### ISSUE TITLE
Implement SnippetPreviewProgressBar component

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#226]
_Copied from https://github.com/Yoast/yoast-components/issues/157#issuecomment-322164816_

We should implement a SnippetPreviewProgressBar component (extended from the ProgressBar component) with the following additions:

>As per https://github.com/Yoast/wordpress-seo/issues/3866, the progress bar should have a few extra design elements:
>
>- A ::before and ::after which is are white boxes of 2px wide, with matching borders on the left and right edges, and place those at the relative positions (left: 30%, right 10%). This will visually make it appear to be 3 separate boxes while keeping it as one progress bar. (ask jip if you need help with this)
>- A text label next to the progress bar on the left which communicates textually the state that the bar is in (_too short, ideal range, too long_). Font is the default font used, size at about 0.75em.
>- When the progress bar reaches the _too long_ section it should turn red. The values for the progress bar should be tweaked a little too, because now there isn't really a _too long_ section to it, it only changes color again once the bar has reached 100% and you keep typing.
>
>Below is a mockup:
>
>![snippet preview progress bars](https://user-images.githubusercontent.com/6073772/29269649-da87a708-80f2-11e7-8086-7ea6c1b70147.png)
>
>New colors are from #222.

**Comment by hedgefield** [comment]
Actually the ::before can move up to about 60%, I noticed you have to type quite a bit before the bar goes from orange to green.

**Comment by IreneStr** [comment]
This has been implemented.
