### ISSUE TITLE
Fix unknown props console error

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#229]
![schermafbeelding 2017-08-16 om 10 01 35](https://user-images.githubusercontent.com/17744553/29353272-f4700d7c-8269-11e7-8189-e37065e00744.png)

**Comment by Xyfi** [comment]
I've figured out that it is caused because material-ui's `IconButton` is used within a `Step` component. 

```
import React from "react";
import styled from "styled-components";

import MuiThemeProvider from "material-ui/styles/MuiThemeProvider";

import muiTheme from "../../../OnboardingWizard/config/yoast-theme";

import { Stepper, Step, IconButton } from "material-ui";

export const SnippetPreviewDiv = styled.div`
	height: 700px;
	width: 100%;
	background-color: white;
`;

/**
 * Returns the SnippetPreview component.
 *
 * @returns {ReactElement} The SnippetPreview component.
 */
export default function SnippetPreview() {
	return (
		<SnippetPreviewDiv>
			<MuiThemeProvider muiTheme={muiTheme}>
				<Stepper linear={false} activeStep={0}>
					<Step>
						<IconButton>
						</IconButton>
					</Step>
				</Stepper>
			</MuiThemeProvider>
		</SnippetPreviewDiv>
	);
}
```

**Comment by Xyfi** [comment]
The problem comes from `StepIndicator` where a `CustomStepButton` is used instead of `material-ui`'s `StepButton`. This `CustomStepButton` is a wrapper around `material-ui`'s IconButton, which should not be used in a `Step`.

**Comment by IreneStr** [comment]
This issue has been moved back to the backlog because it has no priority right now.

**Comment by IreneStr** [comment]
This issue is not relevant anymore.
