### ISSUE TITLE
Features needed in Wizard Components.

### ISSUE THREAD

**Issue by herregroen** [Yoast/yoast-components#240]
In order to resolve Yoast/wordpress-seo#6933 some new features are needed for the Components in the Wizard.

The `Choice` component should support the `html` and `decoration` properties.
* `html` is a string of HTML that should be inserted between the `label` and the `fieldset`.
* `decoration` is the URL of an image that should be inserted on the right side of the component.

There should be a `SocialMediaInput` component that acts like the `Input` component but supports the additional `labelIcon` property.
* `labelIcon` is a string referring to an icon from a social network that should be prepended to the label. For example: the `facebook` value should prepend a facebook icon before the label. The following social networks should be supported:
    * Facebook
    * LinkedIn
    * YouTube
    * Twitter
    * Pinterest
    * Google+
    * Instagram

**Comment by hedgefield** [comment]
I've grouped the issues that require these new features under [this milestone](https://github.com/Yoast/wordpress-seo/milestone/70) on the wordpress seo repo.

**Comment by Xyfi** [comment]
Closing this issue because the relevant changes have been made in other PRs.
