### ISSUE TITLE
Onboarding Wizard Make "Go back to the Yoast SEO Dashbord" a button.

### ISSUE THREAD

**Issue by Xyfi** [Yoast/yoast-components#246]
The sentence at the bottom of the onboarding wizard that allows you to exit the wizard should be an `IconButton`, as shown here:

Change the link in the footer to a proper button, styled the same way as the other wizard buttons, change its copy to Close wizard and return to Yoast SEO dashboard, set the margin to 1em auto, padding to 1em.

<img width="460" alt="9_title_settings_png__11_documents__11_total_pages_" src="https://user-images.githubusercontent.com/5389513/29772340-a4a390f0-8bf8-11e7-95a0-1be4ef4ac14b.png">

**Comment by afercia** [comment]
I'd consider to build this as a link (styled as a button), as it's actually a link that points to a resource, allowing users to navigate from `/admin.php?page=wpseo_configurator` to `/admin.php?page=wpseo_dashboard`.

From a design perspective, I'd consider to shorten the text. The combined effect of uppercase and very long text is a bit too heavy maybe:
`CLOSE WIZARD AND RETURN TO YOAST SEO DASHBOARD`

Also, as discussed at WC London, from an a11y perspective, uppercase text should be avoided: maybe it can be considered acceptable when used for very short UI controls labels (2-3 words) but it's difficult to scan for long text. Ping @hedgefield

**Comment by hedgefield** [comment]
Yeah thanks for bringing it up @afercia  `CLOSE WIZARD` is better. It doesn't matter where you go after you close it, you just want to get outta there ha.

**Comment by boblinthorst** [comment]
This link is not created by the onboarding wizard in yoast components. Instead, is is created in the yoast-seo plugin. I'm guessing because the admin_url is known there.

https://github.com/Yoast/wordpress-seo/blob/trunk/admin/config-ui/class-configuration-page.php#L125

**Comment by afercia** [comment]
Explored a bit this, I'd say there are 2 options:
- stop generating the button with PHP, pass the "back URL" from PHP to the wizard config using the `yoastWizardConfig` localized script, would then need #262  to be expanded to have a LinkButton with icon. Can certainly be done, but not so fast
- faster way: keep the button in PHP and use the styles provided by WordPress `buttons.css` and `dashicon.css` and adjust the styling.
