### ISSUE TITLE
Create YoastButton component

### ISSUE THREAD

**Issue by Xyfi** [Yoast/yoast-components#251]
Create an implementation of the Button with the Yoast look and feel.

Background- and text-colour should be editable.

Don't mind the icon for now.

![29705620-324c17f0-897f-11e7-8c50-687b46f81bdd_png__1632x540_](https://user-images.githubusercontent.com/5389513/29865819-d2e89058-8d76-11e7-8d37-7e0b6c0dc980.png)

Also, implement it in the AlgolioSearcher in the `SearchResultDetail` component as the Back button.

**Comment by afercia** [comment]
Worth noting on My Yoast we're using `normalize.css` that applies some resets also to buttons.
