### ISSUE TITLE
Create YoastLinkButton component

### ISSUE THREAD

**Issue by Xyfi** [Yoast/yoast-components#253]
Requires #252

Create a `LinkButton` with the Yoast look and feel.

Background- and text-colour should be editable.

Don't mind the icon for now.

![29705620-324c17f0-897f-11e7-8c50-687b46f81bdd_png__1632x540_](https://user-images.githubusercontent.com/5389513/29866329-61885c20-8d78-11e7-8a7c-545a1f111d09.png)

Also, implement it in the AlgolioSearcher in the `SearchResultDetail` component as the `View in KB` button. Make sure the `target="_blank"` attribute is set.

**Comment by afercia** [comment]
Trying to switch everything to `display: inline-flex`, there's a problem in Safari 10, investigating:

![screen shot 2017-09-15 at 10 39 09](https://user-images.githubusercontent.com/1682452/30474621-97234cd0-9a04-11e7-9c1f-895ad78a05e6.png)
