### ISSUE TITLE
Wizard: max width causes wrong output

### ISSUE THREAD

**Issue by andizer** [Yoast/yoast-components#287]
The container area (`yoast-wizard-content-container`) for the wizard has a max-width value of 560 which causes unintended output.

I discovered this during the acceptance testing of https://github.com/Yoast/wordpress-seo/pull/7845

The image is rendered to small:
![yoast_seo_ _configuration_wizard](https://user-images.githubusercontent.com/325040/30534616-3fb46030-9c5f-11e7-950b-c6fa8ae40784.png)

What is happening with the text?
![yoast_seo_ _configuration_wizard](https://user-images.githubusercontent.com/325040/30534652-704df684-9c5f-11e7-9391-131b302097d3.png)

See also:
![yoast_seo_ _configuration_wizard](https://user-images.githubusercontent.com/325040/30534698-a3aac746-9c5f-11e7-97d5-fceb250d800a.png)

and here the button are rendered wrong:
![yoast_seo_ _configuration_wizard](https://user-images.githubusercontent.com/325040/30534733-c56e5bc2-9c5f-11e7-967a-f241fa00d4e3.png)

**Comment by Xyfi** [comment]
There is already a fix for that. @herregroen introduced a `fullWidth` property in https://github.com/Yoast/yoast-components/pull/269 for these situations.

Closing this issue so it can be addressed in Yoast/wordpress-seo#7845.
