### ISSUE TITLE
LoadingIndicator: unknown props justify-content, z-index on div tag

### ISSUE THREAD

**Issue by afercia** [Yoast/yoast-components#292]
To reproduce:
- start the yoast components
- go to the Wizard
- click on the second step (so the loading indicator is rendered)
- observe your browser's console:

`Warning: Unknown props 'justify-content', 'z-index' on <div> tag. Remove these props from the element.`

See:
```
const LoadingIndicator = () => (
	<div className="yoast-wizard-overlay-loader">
		<RefreshIndicator
			size={40}
			left={10}
			top={100}
			status="loading"
			style={style.refresh}
			justify-content= "center"
			z-index={11}
		/>
	</div>
);
```

these properties are passed directly to a div element, maybe they should be passed to the style object instead. Even with that, I'm not sure what `justify-content` is supposed to do since, as far as I see, the loading indicator is not a flex container.

**Comment by Xyfi** [comment]
These should just be added to the `style.refresh` object.

**Comment by afercia** [comment]
Yes but `justify-content` does something only on flex containers. Haven't checked in depth, but seems to me that div is `display: inline-block`.
