### ISSUE TITLE
Implement Help Center Toggle Button

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#311]
Implement the Help Center Toggle Button Component.

![help closed](https://user-images.githubusercontent.com/6073772/28922605-2ada3626-785b-11e7-8f5e-8f40580e2c23.png)

## The button
The button is of the same class as all the other My Yoast buttons. It has an icon (fa-question-circle), a label (`Need help?`) and a chevron that points down when the HC is closed, and points up when the HC is open.

The button is horizontally aligned to the middle of the content column. In My Yoast, it is vertically aligned to the top of the page. In the plugin, it appears in the same place it does now (but also middle-aligned).

If possible, clicking the button should animate the opening of the help center paper, it shouldn't just appear. It's fine if the paper is blank during this transition.

(Above description copied from #196)

**Comment by afercia** [comment]
Thinking at this, the button needs a state to update the icon and the `aria-expanded` attribute.
At the same time, the expandable panel below needs a state.
Wouldn't be better to wrap both in a stateful component?

**Comment by IreneStr** [comment]
@andrea The HelpCenter container in WP will have state
