### ISSUE TITLE
Fix Tabs underlining

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#322]
The underlining under the Tabs:
<img width="715" alt="schermafbeelding 2017-09-29 om 12 21 26" src="https://user-images.githubusercontent.com/17744553/31012081-c620a2a0-a510-11e7-9ae2-7be4b1cf0a64.png">

Is not consistent with @hedgefield's design:
![help video](https://user-images.githubusercontent.com/6073772/28927172-25fabdd8-786a-11e7-828d-2ab64a31770f.png)

**Comment by afercia** [comment]
Will be addressed in #310
