### ISSUE TITLE
Algolia searcher layout needs to be fixed in WordPress

### ISSUE THREAD

**Issue by Xyfi** [Yoast/yoast-components#325]
![cursor_and_general_-_yoast_seo_ _local_wordpress_dev_ _wordpress](https://user-images.githubusercontent.com/5389513/31067179-c7ccef4e-a751-11e7-9bb8-70aa180f0c45.png)

**Comment by BramHeijmink** [comment]
If #316 doesn't fix this, pick it up ASAP.
