### ISSUE TITLE
Restructure Yoast Components folder structure

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#339]
We should restructure the Yoast Components folder structure.

Some ideas:
- Use camelcase for all folder names
- Move everything from the `composites/Plugin/Shared` folder to the `composites/basic` folder (but keep in mind the next list item). 
- Only composites should be in the composites folders. Create a separate components folder for non-composites.

**Comment by atimmer** [comment]
Duplicates https://github.com/Yoast/yoast-components/issues/307
