### ISSUE TITLE
Redesign of Support Tab in the HelpCenter

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#341]
For the 5.6 release, we've added a green button to the support tab in the help center of the Premium plugin. This is a temporary solution to make it possible to reopen the HelpScout pop-up. We need to come up with a more definitive design. 

@hedgefield Could you please provide us with a mock-up?

<img width="2368" alt="general_-_yoast_seo_ _test1_ _wordpress" src="https://user-images.githubusercontent.com/17744553/31227281-912b77b4-a9d9-11e7-91a4-97b6c92a79a8.png">
<img width="2363" alt="general_-_yoast_seo_ _test1_ _wordpress 1" src="https://user-images.githubusercontent.com/17744553/31227282-93c570e2-a9d9-11e7-8c57-1ab55be20761.png">

**Comment by hedgefield** [comment]
The popup itself is a bit of a temp solution already ;) it opens the Helpscout beacon, and that's how it used to work before the new design too, but I'd still like to investigate if it's possible to just merge the form into the tab to get rid of the modal altogether, that UX doesn't make much sense.

The trick is that the popup also collects data about the page when it opens/sends, that would need to be triggered on our own tab/send button then.

Who can investigate if this is an option? if not, I'll make a new design for the tab page.

**Comment by hedgefield** [comment]
Ah, a solution comes by way of https://github.com/Yoast/yoast.com/issues/1123!

A message was needed to reassure customers that getting support via the HC is fully secure, unlike email correspondence. That offered a nice opportunity to spice up this empty tab. I've also included the support image from the new homepage.

![help center email security notice](https://user-images.githubusercontent.com/6073772/34870925-f672e4e0-f78b-11e7-8cda-e158c148604d.png)

To be clear, this means that _the Helpscout popup should no longer open automatically_. Only when the button is clicked.

[Support_team.svg.zip](https://github.com/Yoast/yoast-components/files/1625687/Support_team.svg.zip)

```
If you have a problem that you can’t solve with our video tutorials or knowledge base,
you can send a message to our support team. They can be reached 24/7.

Support requests you create here are sent directly into our support system,
which is secured with 256 bit SSL, so communication is 100% secure.
```
