### ISSUE TITLE
videotutorial required prop warning

### ISSUE THREAD

**Issue by afercia** [Yoast/yoast-components#350]
After https://github.com/Yoast/yoast-components/commit/caf5be98c518ca41620aec2818cedc1fefc163b8

`Warning: Failed prop type: The prop `paragraphs[0].className` is marked as required in `VideoTutorial`, but its value is `undefined`.
  in VideoTutorial`

I guess because VideoDescriptionItem has now a `className: PropTypes.string.isRequired` but this prop is actually passed by the parent component.

**Comment by IreneStr** [comment]
Fixed by #358
