### ISSUE TITLE
Consider to move utilities and HoCs to separate files

### ISSUE THREAD

**Issue by afercia** [Yoast/yoast-components#360]
Splitting this out from #359 

Maybe we should consider to move to a separate file utilities and HOCs like `wrapInHeading()`. For example, `makeOutboundLink()` is already in its own file under utils/.

Also, maybe wrapInHeading() should not contain styling, instead styling should be applied on a case by case basis.

**Comment by Xyfi** [comment]
Closing in favour of #307
