### ISSUE TITLE
Implement language notice for users that can't change the language themselves

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#384]
In the reactified content analysis, we show which language we use to analyze the content:
<img width="462" alt="schermafbeelding 2017-11-21 om 13 19 02" src="https://user-images.githubusercontent.com/17744553/33072267-0c2e6066-cebf-11e7-8850-33316463d7c7.png">
This message contains a link to the language settings. The problem is that not all uses can change the language settings. Currently, we've chosen for the pragmatic solution to hide the message when the user can't change the language him/herself. However, the information about the language that is used for the analysis is still useful for those users. Therefore we want to show another message to them, containing something like 'ask your admin to change the language'.

I find it difficult to formulate the message concisely. First proposals:
- Your site language is set to [language]. Ask the administrator of your site to change the language if this is not correct. 
- Your site language is set to [language]. Ask the administrator of your site to change the language if necessary. 

@hedgefield @moorscode Any thoughts on this?

**Comment by moorscode** [comment]
Offtopic: this sounds like something that should be in the Configuration Wizard.

**Comment by IreneStr** [comment]
@moorscode Do you mean as a replacement for this or as an addition?

**Comment by hedgefield** [comment]
Maybe `Your site language is set to [language]. If this is not correct, contact your site administrator.`

**Comment by IreneStr** [comment]
@hedgefield Sounds much better to me. Thanks! Do you prefer that word order over `Contact your site administrator, if this is not correct.`?

**Comment by hedgefield** [comment]
Yes, you want them to feel validated in the problem they're having (_hey this is not correct_) and then offer them the solution (_ah okay I will do that_).
