### ISSUE TITLE
makeOutboundLink prints out an `intl` HTML attribute when using the default element

### ISSUE THREAD

**Issue by afercia** [Yoast/yoast-components#444]
Noticed while working on the content for [the react modals](https://github.com/Yoast/wordpress-seo/issues/5781). 

Most of the times we use `makeOutboundLink` with some styled component, so I guess this issue hasn't surfaced until now. However, when using `makeOutboundLink` with the default element  (which is an `a` link) all the props including `intl` are passed to an actual HTML element.

Thus, the final rendered markup is something like `<a href ...  intl="[object Object]"`

**Comment by IreneStr** [comment]
Put on hold because we'll move away from React Intl soon
