### ISSUE TITLE
Refactor analysisCollapsible to contain a text link button

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#451]
For the content analysis in the sidebar, we need a collapsible header with a text link button instead of an arrow icon in the right corner: 
![34945702-7248fb0c-fa04-11e7-8b50-fbdd14a5df1e](https://user-images.githubusercontent.com/17744553/37831549-3ae2fc86-2ea6-11e8-9dbd-8fe72b30db89.png)

Please refactor the existing analysisCollapsible.
Please branch from `feature/content-analysis-in-sidebar`.

**Comment by atimmer** [comment]
If we refactor it in `yoast-components` do a release, won't it be changed in the current metabox?

**Comment by IreneStr** [comment]
@atimmer I forgot to mention the feature branch 😅

**Comment by atimmer** [comment]
@IreneStr So we'll have two feature branches, one in `yoast-components` and one in `wordpress-seo`.

**Comment by IreneStr** [comment]
Blocked until redesign by @hedgefield (motivated by a11y/UI concerns by @afercia)

**Comment by IreneStr** [comment]
Closed because new design doesn't have text link buttons
![sidebar 1](https://user-images.githubusercontent.com/17744553/38498676-7816a49c-3c05-11e8-900a-98e70b7816c9.png)
