### ISSUE TITLE
Implement sectionWithToggle component

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#455]
Both in the Gutenberg sidebar, as well as in the classic editor sidebar metabox, we'd like to have a cornerstone content toggle:
![sidebar](https://user-images.githubusercontent.com/17744553/38014354-c51a517c-3268-11e8-8479-c54a5b1f8517.png)

Implement a sectionWithToggle component for this that contains a heading, a label and a toggle, like in the image above. The title should be passed as a prop to make this component reusable. Please investigate first how we can make this toggle happen in both editors without duplicate code. Gutenberg already has a toggle component available, which is used in, for example, the document sidebar. If you're going to implement the same toggle in yoast-components, please use the same selected/active styles etc.

Please make sure the font, spacing etc. is consistent with the collapsible headings, like in the above image.

**Comment by hedgefield** [comment]
We won't be doing this for V1 so closing this.
