### ISSUE TITLE
Append UTM tags to knowledge base search results

### ISSUE THREAD

**Issue by jonoalderson** [Yoast/yoast-components#456]
`/composites/AlgoliaSearch/SearchResultDetail.js` retrieves search results for knowledge base entries in the "Need help" / "Knowledge base" panel in the plugin, but these omit UTM tags.

We should append the following to each generated URL:

`?utm_medium=software&utm_source=yoast-seo&utm_campaign=wordpress-support`

**Comment by jdevalk** [comment]
@jono-alderson correct me if I'm wrong but shouldn't it be a hashbang and not a question mark?

**Comment by moorscode** [comment]
Implementation detail: The URL formatting should be injected, as callback, into the component instead of being hard-coded.

**Comment by jono-alderson** [comment]
Ah, yes, let's `#`, not `?`.
