### ISSUE TITLE
Implement HelpSection Component

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#461]
![38248175-d2850cf6-3747-11e8-8953-bca1a204a06a](https://user-images.githubusercontent.com/17744553/38409864-5e5ad3b8-3983-11e8-87a2-2f7f982c6a88.jpg)

The design of the expanded section will follow soon

**Comment by IreneStr** [comment]
Waiting for updated designs by @hedgefield

**Comment by hedgefield** [comment]
Closing because this will be done differently :)
