### ISSUE TITLE
Collapsible panel should use down / up arrows

### ISSUE THREAD

**Issue by afercia** [Yoast/yoast-components#463]
Gutenberg used to use right / down arrows fir the collapsible panels so #449 implemented arrows that way. However arrows have changed in Gutenberg see https://github.com/WordPress/gutenberg/pull/5806 and they now are down / up. This is to be consistent with similar panels in WordPress.

I guess the collapsible panel should update too and use down / up arrows.

**Comment by afercia** [comment]
Also, the icons size might be a problem.

In Gutenberg, the dashicon arrows have a "canvas" of 20 by 20 pixels, but the actual "glyph" is way smaller:

<img width="335" alt="screen shot 2018-04-11 at 12 20 50" src="https://user-images.githubusercontent.com/1682452/38611384-d146ca72-3d83-11e8-8e66-c5c91411a1a7.png">

Instead, the SVG arrows in the yoast-components have a "canvas" of 16 by 16 pixels but the actual glyph is way bigger:

<img width="507" alt="screen shot 2018-04-11 at 12 22 05" src="https://user-images.githubusercontent.com/1682452/38611586-654295e4-3d84-11e8-99a0-2d9e00aedd98.png">

Not sure what the best option would be here:
- refactor "our" SVG icons to match the WP / Gutenberg ones (costly, maintenance issues...)
- just use the Gutenberg dashicons

**Comment by IreneStr** [comment]
The dashicons are currently not available outside Gutenberg yet, so for now, we'll keep using 'our' SVG icons.
