### ISSUE TITLE
Implement keyword input field component

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#466]
![sidebar](https://user-images.githubusercontent.com/17744553/38664853-149c119e-3e3b-11e8-8cb0-65c8142e9826.png)

Not in the image:
- The input filed should have the `<label>` Focus keyword 
- The input field border should turn red when it contains comma-separated keywords. In that case, there should also be a warning message. See  https://github.com/Yoast/wordpress-seo/issues/9179#issuecomment-378182987 (scroll down for the latest version of the message).
- The input field should have an onChange prop so that we can change the state when there is a change.

**Please branch from the feature/content-analysis-in-sidebar feature branch.**

**Comment by afercia** [comment]
To make the message accessible, we should either use a `speak` message or do as in the MyYoast account section, where we use `role="alert"` on the element that appears on the page (see screenshot below):

<img width="547" alt="screen shot 2018-04-12 at 11 00 00" src="https://user-images.githubusercontent.com/1682452/38667430-b24c11ae-3e41-11e8-9692-13aaef738336.png">

The yellow box has a `role="alert"`, which makes screen readers announce its content.
