### ISSUE TITLE
Implement an SEO analysis component

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#475]
<img width="300" alt="schermafbeelding_2018-07-10_om_08_39_46" src="https://user-images.githubusercontent.com/17744553/42493392-289d4de8-841d-11e8-84a1-ea60c67b2e7d.png"> <img width="300" alt="schermafbeelding_2018-07-10_om_08_40_00" src="https://user-images.githubusercontent.com/17744553/42493514-99d55032-841d-11e8-86aa-932d0254c259.png">

Important: 
- 'Focus keyword:' and 'Analysis results:' should be `<label>`s. When in doubt, discuss with @afercia what's the best way to go a11y-wise 

Needs #466 
Needs #476

**Please branch from the feature/content-analysis-in-sidebar feature branch.**

**Comment by afercia** [comment]
Any design for the multiple focus keyword on Premium?

**Comment by IreneStr** [comment]
@afercia From an older mockup, without help text: 

<img width="300px" alt="multiple keyword" src="https://user-images.githubusercontent.com/17744553/39114090-121e16e6-46de-11e8-833e-d7c31e9e3afe.png">
