### ISSUE TITLE
Handle special characters correctly in the React mobile snippet preview

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#486]
<img width="632" alt="schermafbeelding 2018-05-08 om 15 07 01" src="https://user-images.githubusercontent.com/17744553/39758943-a095a746-52d1-11e8-9ece-6479b7952122.png">

## Decision to make
Do we want to strip special characters or handle then in another way, or keep them?

**Comment by IreneStr** [comment]
@jono-alderson Sounds like a plan! Let's try that

**Comment by IreneStr** [comment]
Removed from the queue, because the React desktop preview currently behaves the same as the legacy desktop preview. A separate issue about the URI encoding will be created.

**Comment by atimmer** [comment]
I guess, just close this then.
