### ISSUE TITLE
GDPR-compliant copy on newsletter signup

### ISSUE THREAD

**Issue by hedgefield** [Yoast/yoast-components#512]
You now receive a MyYoast account when you sign up for the newsletter, so we need to adjust the copy of the form in the configuration wizard to inform users of that, to comply with GDPR regulations.

- [ ] Remove the `Stay up-to-date` line and mail icon.

- [ ] Change the copy to:

> Sign up for our newsletter if you would like to keep up-to-date about Yoast SEO for WordPress, other cool plugins by Yoast, and interesting news and tips from the world of SEO.
> 
> **Includes a free MyYoast account which gives you access to our free SEO for Beginners course!**

- [ ] Remove the `Name` input field.

- [ ] Add a line of 10px copy below the input field that says:

> Yoast respects the GDPR. Read our [privacy policy](https://yoast.com/privacy-policy/) on what happens with your personal information.

**Comment by CarolineGeven** [comment]
Moved to https://github.com/Yoast/wordpress-seo/issues/9665
