### ISSUE TITLE
Snippet preview: highlightKeyword doesn't work (missing keyword prop)

### ISSUE THREAD

**Issue by afercia** [Yoast/yoast-components#516]
Seems to me the keyword is not highlighted in the url and description (if present) for a couple reasons:

- `SnippetPreview` expects a `keyword` prop, seems to me it's not passed anywhere and the default is empty string
- even if it's passed, the highlighting would work only in the desktop view (edit: won't work on the url, while it works on the description). Not sure if that's intentional, see https://github.com/Yoast/yoast-components/blob/c52c1242e5b79238a86ea2cab5c1fa5ae314c014/composites/Plugin/SnippetPreview/components/SnippetPreview.js#L475

**Comment by atimmer** [comment]
The second point I don't know about. Should we highlight the keyboard in breadcrumb style?

**Comment by afercia** [comment]
Honestly I'm not sure. Does Google still highlights search terms in the url in the first place? /Cc @jdevalk

**Comment by boblinthorst** [comment]
Though not a be all end all, a quick tests shows that google doesn't seem to highlight the search term in the url. Here's a google search for the term "awesome"
<img width="580" alt="awesome_-_google_search" src="https://user-images.githubusercontent.com/11849359/39923700-0fbef8fc-5525-11e8-8f82-60aaa82fffda.png">

**Comment by boblinthorst** [comment]
When searching with google for the term `awesome`, this is what a result looks like:

<img width="580" alt="awesome_-_google_search" src="https://user-images.githubusercontent.com/11849359/39926999-33c3baba-5531-11e8-97e7-feb7407872a6.png">

the search term seems to be highlighted in the description, not in the title or the slug. 

When doing the same search on a mobile phone, the keyword isn't highlighted anywhere.
