### ISSUE TITLE
Snippet preview: missing "locale" prop

### ISSUE THREAD

**Issue by afercia** [Yoast/yoast-components#518]
As far as I see, the SnippetPreview component needs a `locale` prop to work **prop**erly. For example, see `highlightKeyword > transliterate` where the transliteration needs a locale otherwise it won't work.

Seems to me there's just a default locale prop `locale: "en_US"` and a prop is not passed anywhere. I guess it should be passed by the parent component `SnippetEditor`.

Worth also noting the transliteration needs a two characters locale, e.g. `da` for Danish, while it seems we're using an ISO/Posix `language_region` notation e.g. `"en_US"`.

Edit: additionally, I guess the actual locale to use should be related to the site language, not the user language.

**Comment by Xyfi** [comment]
While working on this issue I also noticed there is no way to pass a keyword to the snippet editor. And since the transliteration is only used in highlighted keywords, i'll fix this in this issue aswell.
