### ISSUE TITLE
Example code react using Yoast Components?

### ISSUE THREAD

**Issue by vndevil** [Yoast/yoast-components#531]
Hi support,

Can you share some code using Yoast SEO analysis component in REACT like in Wordpress???

Many thanks

**Comment by CarolineGeven** [comment]
Hi @vndevil. What is it exactly you want to achieve?

The react code for the analysis can be found here: https://github.com/Yoast/wordpress-seo/blob/trunk/js/src/components/contentAnalysis/Results.js

Does this answer your question?
