### ISSUE TITLE
Selection carets not working in firefox

### ISSUE THREAD

**Issue by boblinthorst** [Yoast/yoast-components#532]
### Please give us a description of what happened.

The selection carets are not working in firefox. In the screenshot, I have selected the meta description, but the visual aid to make that clear is missing:

<img width="630" alt="yoast_components_and_my_short_story___ _local_wordpress_test_ _wordpress" src="https://user-images.githubusercontent.com/11849359/40100027-c53b6420-58e2-11e8-884c-e9c612899b22.png">

### Please describe what you expected to happen and why.

For them to be present, as they are in chrome, for instance. Here I'm selecting the title in chrome:

<img width="571" alt="yoast_components" src="https://user-images.githubusercontent.com/11849359/40100259-9b42619a-58e3-11e8-90e7-c7c0d5f72174.png">

### How can we reproduce this behavior?
See above headers.

### Technical info
* yoast-components version: develop

**Comment by afercia** [comment]
When touching this part of the code, please see also #503

**Comment by vndevil** [comment]
@boblinthorst  can you share with me demo code using yoast-components in reactjs ??

**Comment by afercia** [comment]
Looking a bit into this, seems something related to encoding. Apparently Chrome is less strict, while Firefox expects all characters to be encoded. Worth noting `encodeURI()` does _not_ encode certain characters like `=, ., :, /`. Using a [fully encoded string](https://meyerweb.com/eric/tools/dencoder/) works.

**Comment by afercia** [comment]
Seems also IE 11 doesn't like encoding used for the SVG (I guess XML5602 is a cryptic error related to the SVG):

![screenshot 130](https://user-images.githubusercontent.com/1682452/40170479-d7a36400-59c8-11e8-8007-4a54e062ab9c.png)
