### ISSUE TITLE
Snippet editor Slug input field allows slashes to be typed, but they are converted to dashes on save.

### ISSUE THREAD

**Issue by Xyfi** [Yoast/yoast-components#533]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/wordpress-seo/blob/trunk/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

The snippet editor slug field accepts slashes that are converted to `›` by the mobile snippet preview breadcrumbs.

<img width="600" alt="edit_post_ _local_wordpress_dev_ _wordpress" src="https://user-images.githubusercontent.com/5389513/40105219-9eb5bd0e-58f2-11e8-8d18-b71d094d907a.png">

On save, the slash is converted to a dash, which is to be expected because slugs are only allowed to contain lowercase letters, numbers and dashes. Other special characters are also removed on save, but they do not affect the formatting of the breadcrumbs.

### Please describe what you expected to happen and why.

I expect slashes not to be allowed or automatically to be converted to dashes in the editor.

### How can we reproduce this behavior?
1. Type a slug with slashes and notice the additional breadcrumb being created.
2. Save the post.
3. Notice that the breadcrumb has been concatenated into one slug.

### Technical info
* yoast-components version:

**Comment by maartenleenders** [comment]
Won't fix, this is unexpected user behaviour, decision by Omar.
