### ISSUE TITLE
Snippet variables inserter

### ISSUE THREAD

**Issue by omarreiss** [Yoast/yoast-components#552]
Add a button to insert snippet variables.

What the button basically does, is insert a `%` which will trigger the autocomplete. This also makes that behavior more discoverable. Designs coming up shortly by @uxkai

**Comment by uxkai** [comment]
@omarreiss 

In the design below I added `%` buttons to `SEO title` en `Meta description` field.
![inserter](https://user-images.githubusercontent.com/34368416/40481335-6e5f939a-5f51-11e8-83a7-6ffbaf48ba11.png)

**Comment by uxkai** [comment]
@omarreiss, please see the design variations below:

- Different icons

![variation1](https://user-images.githubusercontent.com/34368416/40483079-1b795408-5f57-11e8-90d9-d8ede52f8946.png)

---

![variation2](https://user-images.githubusercontent.com/34368416/40483085-1f015e22-5f57-11e8-8002-16733c6a1f88.png)

---

![variation3](https://user-images.githubusercontent.com/34368416/40483090-21220968-5f57-11e8-92ad-a2f8a25ddd9c.png)

- Button with text (next to the title)

![variation4](https://user-images.githubusercontent.com/34368416/40483142-449e90e6-5f57-11e8-81b7-85356c2ce60c.png)

- Button with text (below the title)

![variation5](https://user-images.githubusercontent.com/34368416/40483171-5a1db866-5f57-11e8-9403-6f5af64c8581.png)

- Toolbar with text (below the title, at the top of the input field)

![variation6](https://user-images.githubusercontent.com/34368416/40483351-f8ce50c4-5f57-11e8-9671-6f3ed449dd75.png)

**Comment by uxkai** [comment]
I like your idea with the icon @omarreiss.

1.  
![variation7](https://user-images.githubusercontent.com/34368416/40617634-28e759d8-628f-11e8-8133-b6c990a52763.png)

---

2. 
![variation8](https://user-images.githubusercontent.com/34368416/40617635-28fe5d5e-628f-11e8-8d3d-5dceff1c882e.png)

**Comment by hedgefield** [comment]
Spitballing here, but does the button even need the `snippet variable` part? I'd say `Insert` triggers more curiosity than `insert snippet variable` which is a term that people may not know about.

**Comment by omarreiss** [comment]
It's a term people need to learn. Second design is what we're going to build and test.

**Comment by igorschoester** [comment]
@omarreiss  @hedgefield @uxkai 
Here is a screenshot how it looks so far.
<img width="360" alt="insert snippet variable button" src="https://user-images.githubusercontent.com/35524806/40715148-ed46bf46-6404-11e8-8f0c-c6a2bbcfa6a4.png">

I have some questions:
- On an iPhone 5 (320px) it does not fit next to the field. With 328px it fits. What would be a good solution for this?
- The corners are rounded to match the existing icon button design. With the bottom corners not rounded it looks connected. See screenshot below. Is that better?

<img width="354" alt="bottom border" src="https://user-images.githubusercontent.com/35524806/40716472-6fdd7c3e-6409-11e8-9c60-85b04e2696bf.png">

**Comment by hedgefield** [comment]
I would consider aligning the buttons on the left on mobile, under the field labels. And I like the idea of the square corners at the bottom 👍 It could also work as a classic button if there was a bit of space between field and label+button, but I'm not sure if others prefer the button to be attached to the field for UX reasons.

**Comment by omarreiss** [comment]
Some space between the button and the input field seems best to me. Let's keep the styling of that button consistent. I agree with aligning the button to the left on a new line on mobile.

**Comment by igorschoester** [comment]
Thank you both, will do. One more question for you @omarreiss 
What to do when a user has some text selected when he presses the button? Does the text get replaced with a `%`?

**Comment by omarreiss** [comment]
@igorschoester I'd do what is the least work.
