### ISSUE TITLE
Use snippet variables nicenames when selecting them in the mentions plugin

### ISSUE THREAD

**Issue by boblinthorst** [Yoast/yoast-components#577]
In https://github.com/Yoast/yoast-components/pull/566, Nicenames are introduced for snippet variables. But these nicenames weren't used when selecting a snippet variable in the mentions plugin. So this needs to be added.

<img width="562" alt="yoast_components-2" src="https://user-images.githubusercontent.com/11849359/41023098-b68b1a26-696b-11e8-9285-237eccf3da48.png">

Needs https://github.com/Yoast/wordpress-seo/pull/10065
Needs https://github.com/Yoast/yoast-components/issues/577

**Comment by maartenleenders** [comment]
As an extra spec, this PR will also contain a fix for the `ct_` nicenames:
* the label should omit the `ct_` part, capitalize the first letter, and transform underscores into spaces.
