### ISSUE TITLE
Create a toggle component

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#626]
<img width="521" alt="schermafbeelding 2018-06-28 om 08 57 47" src="https://user-images.githubusercontent.com/17744553/42018118-620ba1bc-7ab1-11e8-9c18-fe076ee2b868.png">
This toggle component will be used to mark cornerstone content in the sidebar, but probably 
also in other places later. Therefore, make it flexible. Use backported Gutenberg components when possible.

#### Context of the toggle:
<img width="240" alt="sidebar 7 expanded" src="https://user-images.githubusercontent.com/6073772/40122626-87e97e26-5924-11e8-8c82-ac5a7ead9b00.png">

**Comment by omarreiss** [comment]
So we decided to go with MyYoast toggles.
