### ISSUE TITLE
Create a sidebar button component

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#627]
Create a sidebar button component that can be used for the following things: 
<img width="551" alt="schermafbeelding 2018-06-28 om 09 02 23" src="https://user-images.githubusercontent.com/17744553/42018329-10de8d3a-7ab2-11e8-97c0-0c90936040de.png">
NB. Please think about a better name than sidebarButton, if possible.

!! **Branch from feature/content-analysis-in-sidebar** !!

#### Context of the buttons:
<img width="240" alt="sidebar 7 expanded" src="https://user-images.githubusercontent.com/6073772/40122626-87e97e26-5924-11e8-8c82-ac5a7ead9b00.png">

Needs #649

**Comment by afercia** [comment]
@tim when you have a chance: I was able to copy the "gear" icon from dashicons but I'd need some help for the "dock to the bottom" one 🙂thanks!

**Comment by hedgefield** [comment]
[Here's the icons for the docking icon.](https://github.com/Yoast/yoast-components/files/2175937/metabox.docking.icons.zip)
