### ISSUE TITLE
Implement custom fillFieldDraftJS and fillClearFieldDraftJS for automated testing

### ISSUE THREAD

**Issue by dariaknl** [Yoast/yoast-components#637]
As agreed with @atimmer the following functions _fillFieldDraftJS_ and _fillClearFieldDraftJS_ are to be introduced in [automated testing](https://github.com/Yoast/plugins-automated-testing). The issue is created here in order to be picked up in the process. The idea is to help me to write this function so I can test it immediately in the automated test scenarios.

More details: fillField is currently implemented in codeceptjs as follows:
https://github.com/Codeception/CodeceptJS/blob/master/lib/helper/Puppeteer.js#L872
```  async fillField(field, value) {
    const els = await findFields.call(this, field);
    assertElementExists(els, field, 'Field');
    const el = els[0];
    // await el.focus();
    const tag = await el.getProperty('tagName').then(el => el.jsonValue());
    const editable = await el.getProperty('contenteditable').then(el => el.jsonValue());
    if (tag === 'INPUT' || tag === 'TEXTAREA') {
      await this._evaluateHandeInContext(el => el.value = '', el);
    } else if (editable) {
      await this._evaluateHandeInContext(el => el.innerHTML = '', el);
    }
    await el.type(value, { delay: 10 });
    return this._waitForAction();
  }
```

It is proposed to implement custom fillFieldDraftJS based on fillField locating element for example within "DraftEditor-root".
The same is supposed to be implemented for fillClearFieldDraftJS based on clearField of codeceptjs.

**Comment by IreneStr** [comment]
Some clarifications:
- This needs to be built inside the automated testing framework.
- @dariaknl would like to pair on this. Please contact her when you pick up this issue.

**Comment by Xyfi** [comment]
The `fillField` function allows draftjs field (`contenteditable` elements) to be filled. @darianl needed an easy way to access them so I added an id to these field instead.
