### ISSUE TITLE
Create upsell component

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoast-components#661]
## Context
<img width="478" alt="schermafbeelding_2018-07-13_om_09_15_17" src="https://user-images.githubusercontent.com/17744553/42677873-6f7046a0-867d-11e8-9085-cfd183392565.png">

Create an upsell component that is going to be used in the sidebar and metabox. The component should contain one or more paragraphs, one or more bullet points (with plusses), and a button with a paragraph underneath. The paragraph under the button and the button should be 'connected' to each other using `aria-describedby`.

**Comment by afercia** [comment]
May I suggest to try to get the list of benefits from a centralized place? We've had and still have a bit of inconsistency across all these lists. See https://github.com/Yoast/wordpress-seo/issues/9120

We've recently made an attempt to try to reduce inconsistency, see https://github.com/Yoast/wordpress-seo/commit/067cfa4bfa6041f939f63d7572310b9dbc2ba298 and https://github.com/Yoast/wordpress-seo/commit/63e0f3193a951d289cbe3988e9dcd6a821f189ca
