### ISSUE TITLE
Styling improvements for the Analysis results. 

### ISSUE THREAD

**Issue by boblinthorst** [Yoast/yoast-components#671]
Split off from https://github.com/Yoast/yoast-components/pull/492.

The PR became way too big, and addressing the styling comments in the PR would make it even bigger than it already is.

In the words of @maartenleenders:
The styling in the ContentAnalysis seems to be slightly below our standards, but that is my opinion. I think we'd do well to give everything a little more 'breathing room' with padding/margins. @hedgefield has offered to sit in on a little styling session to improve things. I would also be fine if you split this up into a new issue, as this PR has become quite big.

**Comment by hedgefield** [comment]
I checked out the components standalone app and did some tweaking. Here are some improvements:

- For each collapsible section, add `margin-bottom: 8px`
- For each collapsible section header, set `font-size: 1.1em` and `padding: 8px 16px`
- For each analysis result, set `padding: 8px 16px`

I assume the margin/padding around all the components is set globally on the sidebar element? Is it possible to remove it there and add it to each component individually? It's a little cumbersome, but it produces better results for the focus indicator. Or would that be too much inefficient CSS?

![3](https://user-images.githubusercontent.com/6073772/43311117-bcb113c4-9189-11e8-9ee8-c70ea8d99c24.png)

**Comment by afercia** [comment]
One important thing to consider is that the ContentAnalysis uses a custom implementation of the "collapsible header", duplicating great part of the code. I'd tend to think it shouldn't do this, and just reuse the `Collapsible` component which is going to be refactored in #653 and #654

**Comment by afercia** [comment]
> For each collapsible section header, set font-size: 1.1em

I'd need the value in pixels for this, as the em one varies depending on the context (standalone app or within the meta box) and i've also made other changes.

> For each analysis result, set padding: 8px 16px

Do you mean each group of results or each single item in a group of results?

**Comment by hedgefield** [comment]
> I'd need the value in pixels for this, as the em one varies depending on the context (standalone app or within the meta box) and i've also made other changes.

I'd say 14 then, just a tad bigger than the default 13px sidebar font size.

> Do you mean each group of results or each single item in a group of results?

Each single item.

**Comment by afercia** [comment]
> Each single item.

OK but I'd suggest to check it again once it's in the meta box. Right now, with the changes made on #676 the items already have a good spacing (see below). I'm afraid adding more padding will make them way too spaces, but again this needs to be checked in the meta box.

<img width="742" alt="screen shot 2018-07-29 at 17 21 39" src="https://user-images.githubusercontent.com/1682452/43382318-c45fecda-93d7-11e8-9c2b-da042d2c1e12.png">

**Comment by hedgefield** [comment]
Ahh yes this looks very good, carry on.

**Comment by afercia** [comment]
We need to keep this open to adjust the left and right padding on the StyledSection in the meta box.

Now that the analysis has ben changed to have its own left and right paddings, the ones in the StyledSection add too much space. Moving to the queue.
