### ISSUE TITLE
Synonyms explanation text size is too small

### ISSUE THREAD

**Issue by afercia** [Yoast/yoast-components#688]
When rendered in the Premium sidebar, the `ExplanationText` for synonyms is really too small. Its computed font size is 10.4 pixels (.8em of 13 pixels):

<img width="309" alt="screen shot 2018-08-03 at 14 51 23" src="https://user-images.githubusercontent.com/1682452/43644053-a4a9b69c-972d-11e8-8fd9-cb24eff9521e.png">

I tend to think in WordPress there shouldn't be anything with a font size smaller than 13 pixels. Outside of WordPress many applications already have increased their base font size to bigger values. /Cc @hedgefield

**Comment by hedgefield** [comment]
@moorscode, @maartenleenders and I noticed this too. The size is okay on 1080p resolutions and below, but not on anything above - and that's where we're heading. So let's put these at 13px, and maybe we can make them less obtrusive with a lighter color like #646464.

**Comment by afercia** [comment]
Cool, will try the new color.

On a side note, we should avoid to throw in random values like `0.8em` which compute to values in pixels with decimals. Screens are not able to split pixels, yet. Also, browsers have different rounding algorithms. When using `em`, we should always use a value that computes to a value in pixels without decimals.

**Comment by afercia** [comment]
Also, this field shouldn't have an `aria-label` because it already has an associated `<label>` element.

**Comment by afercia** [comment]
For completeness, this is the small text in the metabox:

<img width="894" alt="screen shot 2018-08-03 at 15 43 19" src="https://user-images.githubusercontent.com/1682452/43646025-fc6e3f5a-9733-11e8-9451-2857cd901823.png">
