### ISSUE TITLE
Don't exclude tests from the ESLint config

### ISSUE THREAD

**Issue by afercia** [Yoast/yoast-components#737]
We shouldn't exclude test files from being linted:

https://github.com/Yoast/yoast-components/blob/4d5f52ecfde449a2f0a3fd97d598d8667a1f0f58/Gruntfile.js#L14-L20

**Comment by atimmer** [comment]
Added to that: 

* All JS files should be linted, instead of having an inclusion list of files, we should have an excluded files list.
