### ISSUE TITLE
Fix the standalone app

### ISSUE THREAD

**Issue by afercia** [Yoast/yoast-components#759]
The standalone app is currently broken, see below:

<img width="927" alt="screen shot 2018-10-15 at 14 02 16" src="https://user-images.githubusercontent.com/1682452/46953074-05bc6900-d08d-11e8-9e91-985b5b8fa6cc.png">

Not sure about the first error, the other ones seem missign default exports (I've seen some have been changed to `module.export....`?

**Comment by IreneStr** [comment]
Please consult with Team Lingo because these errors seem to be caused by changes in YoastSEO.js

**Comment by afercia** [comment]
Seems the standalone app is now working, as the related `module.export` were changed. The app runs, tests pass. Closing.
