### ISSUE TITLE
Disable autocomplete browser functionality for Keyphrase fields

### ISSUE THREAD

**Issue by moorscode** [Yoast/yoast-components#792]
### Please give us a description of what happened.

When typing into the keyphrase field, I get suggestions from the browser from other keyphrases I've entered on other posts. This is because the field is identifiable thus making the browser believe it's desired to show related data.

As the keyphrase field is something that is intended to be unique, providing suggestions that have already been used is the opposite of what we want it to be used for.

Adding an `autocomplete="off"` to the field should fix this problem.

### Please describe what you expected to happen and why.

Pressing the "down" arrow-key on the keyboard in the keyphrase field reveals the following suggestions on my local installation:

<img width="482" alt="screen shot 2018-12-11 at 10 16 27" src="https://user-images.githubusercontent.com/2005352/49790159-dc872480-fd2d-11e8-9038-c097bb5788a8.png">

### How can we reproduce this behavior?
1. Enter keyphrases for several posts/pages
2. Press the "down" arrow-key on a keyphrase field or start a keyphrase the same way as another keyphrase you've entered on the other posts/pages

### Technical info

* If relevant, which editor is affected (or editors): 
- [x] Classic Editor
- [x] Gutenberg
- [ ] Classic Editor plugin

* Which browser is affected (or browsers): 
- N/A

**Comment by afercia** [comment]
Acceptance 👍
