### ISSUE TITLE
Automate makeOutboundLink `rel` attribute handling

### ISSUE THREAD

**Issue by afercia** [Yoast/yoast-components#828]
In MyYoast, see https://github.com/Yoast/my-yoast/pull/2279, we've made the `Link` component able to automatically handle the `rel` attribute.

As per https://github.com/Yoast/wordpress-seo/issues/4605#issuecomment-425409923, the desired behavior is:

* use `noopener` for all the non-yoast.com external links
* omit it for the yoast.com links (including shortened links)

In WordPress, `noreferrer` is redundant, especially after https://core.trac.wordpress.org/changeset/41741 see 
https://core.trac.wordpress.org/ticket/42036

Currently, each time we don't want a `rel` attribute rendered, we're explicitly passing a `rel={ null }`. This is prone to human errors and can be easily forgotten. `makeOutboundLink` should handle this automatically.

**Comment by hwinne** [comment]
12262 (Free) still needs action,
2259 (Premium) CR Done 👍 ,
9 (Monorepo) CR Done 👍

**Comment by afercia** [comment]
Moving to code review done as the previous PR was already CR'ed.
